using HC.AI.Identity.BL.OcrDocument;
using HC.AI.Identity.Models.OcrDocument;
using Microsoft.AspNetCore.Mvc;

namespace HC.AI.Identity.Api.Controllers;

[ApiController]
[Route("api/[controller]")]
public class DocumentController : ControllerBase
{
    private readonly IOcrDocumentBL _ocrDocumentBL;

    public DocumentController(IOcrDocumentBL ocrDocumentBL)
    {
        _ocrDocumentBL = ocrDocumentBL;
    }

    /// <summary>Upload a document for OCR extraction. Registers the record and returns its DCN.</summary>
    [HttpPost("upload")]
    [Consumes("multipart/form-data")]
    public async Task<IActionResult> Upload([FromForm] string documentType, [FromForm] string? groupNumber, IFormFile file)
    {
        if (file is null || file.Length == 0)
            return BadRequest(new OcrDocumentResponse { IsNotValid = true, Message = "No file provided." });

        var model = new OcrDocumentsModel
        {
            OcrDocumentRequest = new OcrDocumentRequest
            {
                DocumentType = documentType,
                GroupNumber = groupNumber,
            },
            OcrDocumentItem = new OcrDocumentItem
            {
                FileName = Path.GetFileNameWithoutExtension(file.FileName),
                FileExtension = Path.GetExtension(file.FileName).TrimStart('.').ToLower(),
                BlobSize = file.Length,
            }
        };

        var result = await _ocrDocumentBL.Upload(model);
        if (result.IsNotValid)
            return BadRequest(result.OcrDocumentResponse);

        return Ok(result.OcrDocumentResponse);
    }

    /// <summary>
    /// Registers a document already uploaded to Blob Storage by fa_upload_doc.
    /// DCN/GRP are already generated by the caller — this only persists the record.
    /// </summary>
    [HttpPost("register")]
    public async Task<IActionResult> Register([FromBody] RegisterDocumentRequest request)
    {
        var model = new OcrDocumentsModel { RegisterDocumentRequest = request };
        var result = await _ocrDocumentBL.Register(model);
        if (result.IsNotValid)
            return BadRequest(result.OcrDocumentResponse);

        return Ok(result.OcrDocumentResponse);
    }

    /// <summary>Returns all active OCR documents ordered by creation date descending.</summary>
    [HttpGet]
    public async Task<IActionResult> GetAll()
    {
        var result = await _ocrDocumentBL.GetAll(new OcrDocumentsModel());
        return Ok(result.OcrDocumentItems);
    }

    /// <summary>Returns a single document by its primary key.</summary>
    [HttpGet("{id:int}")]
    public async Task<IActionResult> GetById(int id)
    {
        var model = new OcrDocumentsModel { OcrDocumentItem = new OcrDocumentItem { Id = id } };
        var result = await _ocrDocumentBL.GetById(model);
        if (result.IsNotValid)
            return NotFound(result.Message);
        return Ok(result.OcrDocumentResponse);
    }

    /// <summary>Returns all documents belonging to a batch group number.</summary>
    [HttpGet("group/{groupNumber}")]
    public async Task<IActionResult> GetByGroupNumber(string groupNumber)
    {
        var model = new OcrDocumentsModel
        {
            OcrDocumentRequest = new OcrDocumentRequest { GroupNumber = groupNumber }
        };
        var result = await _ocrDocumentBL.GetByGroupNumber(model);
        return Ok(result.OcrDocumentItems);
    }

    /// <summary>Soft-deletes a document by its primary key.</summary>
    [HttpDelete("{id:int}")]
    public async Task<IActionResult> Delete(int id)
    {
        var model = new OcrDocumentsModel { OcrDocumentItem = new OcrDocumentItem { Id = id } };
        var result = await _ocrDocumentBL.Delete(model);
        if (result.IsNotValid)
            return NotFound(result.Message);
        return Ok(result.Message);
    }
}
