namespace AI.HR.Models.OcrDocument;

/// <summary>
/// Inbound payload from fa_upload_doc (Azure Function) after it has already
/// uploaded the file to Blob Storage and generated the DCN/GRP. AI.HR.Api
/// only persists what it's given here — it does not generate numbers itself.
/// </summary>
public class RegisterDocumentRequest
{
    /// <summary>Unique document control number, generated by fa_upload_doc — DCN-YY-MM-DD-HH-mm-ss.</summary>
    public string DocumentNumber { get; set; } = string.Empty;

    /// <summary>Shared group number for batch uploads, generated by fa_upload_doc — GRP-YY-MM-DD-HH-mm-ss.</summary>
    public string? GroupNumber { get; set; }

    public string FileName { get; set; } = string.Empty;
    public string FileExtension { get; set; } = string.Empty;
    public string DocumentType { get; set; } = string.Empty;

    /// <summary>Azure Blob Storage URL — already uploaded by fa_upload_doc.</summary>
    public string BlobUrl { get; set; } = string.Empty;

    /// <summary>File size in bytes.</summary>
    public long BlobSize { get; set; }
}
